
# 服务器
server:
  port: 8001  # 服务端口号


# spring
spring:
  application:
    name: microservicecloud-dept  # 微服务名称 ☆ 名称一般不和别的微服务一致，除非要使用负载均衡功能
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 驱动包类型  我一般将它注释掉
    driver-class-name: com.mysql.cj.jdbc.Driver  # mysql驱动包
    url: jdbc:mysql://localhost:3306/test1?serverTimezone=GMT%2B8  # 数据库url
    username: root  # 数据库登录用户名
    password: mysql # 数据库登录密码
    dbcp2:
      min-idle: 5           # 数据库连接池的最小维持连接数
      initial-size: 5       # 初始化连接数
      max-total: 5          # 最大连接数
      max-wait-millis: 200  # 等待连接获取的最大超时时间


# Mybatis
mybatis: 
  config-location: classpath:mybatis/mybatis.cfg.xml     # mybatis配置文件所在路径
  type-aliases-package: com.myjava.springcloud.entities  # 所有Entity别名类所在包
  mapper-locations:                                       # mapper映射文件
    - classpath:mybatis/mapper/**/*.xml


# Eureka
eureka:

  # eureka client
  client: 
    server-url:
        defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  # 要注册的Eureka的服务端地址
  instance:
      instance-id: microservicecloud-dept8001 # 在Eureka服务端显示的实例名称
      prefer-ip-address: true # 在服务端鼠标虚浮在此实例上时是否显示对应的ip地址

  # eureka server
  instance: eureka7003.com # eureka服务端的实例名称
  client:
    register-with-eureka: false # 表示不向注册中心注册自己
    fetch-registry: false # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/



# feign
feign:
  hystrix:
    enabled: true


# zuul
zuul:
  prefix: /mytest
  ignored-services: "*"
  routes: 
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**


# info  访问:http://localhost:8001/info出现的内容
info:
  app.name: myservice8001
  company.name: www.smx.com
  build.artifactid: $project.artifactId$
  build.version: $project.version$



