server:
  port: 8001

spring:
  application:
    name: microservicecloud-demo

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-demo8001   #自定义服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址

